### ISSUE TITLE
Jäsenen kentät

### ISSUE THREAD

**Issue by zouppen** [HacklabJKL/mulysa#1]
Tällaiset kentät olisi hyvä saada jäsenen tietoihin. En tiedä mitä tukia nyt, mutta näitä me tarvittaisiin:

- [ ] Oikeus saada avain (varsinainen ovenavausoikeus on tämä JA korkeampi jäsenmaksuluokka) (tyyppi: `bool`)
- [ ] Oikeus etäkäyttää kerhon laitteita, kuten 3D-tulostin (tyyppi: `bool`)
- [ ] Infran ylläpito-oikeus. Kirjautumisoikeus Unifiin yms. jos jaksetaan joskus konffata. (tyyppi: `bool`)
- [ ] Radioamatöörikutsu. käytetään tiedottamisen kohdentamisessa ja ehkä tulevaisuudessa QSL-korttien valittämisessä (tyyppi: `string`, käyttäjän muokattavissa)
- [ ] MXID eli matrix-käyttäjä-id. Voi käyttää viestinnässä ja chattiboteissa, korvaisi nykyisen nickin eksaktimmalla muotoilulla. Telegram-käyttäjien osalta voidaan käyttää `@_telegram...@hacklab.fi` -muotoilua johon voi myös lähettää viestejä. (tyyppi: `string`, käyttäjän muokattavissa)

**Comment by zouppen** [comment]
These fields are still relevant. Some of them may be already implemented, this is just a list of should-have features. Please update the task if it contains features which are already there.

**Comment by braaar** [comment]
We hav split these things up into different issues. See #6, #7 , #8 , #9, #10
